version: 0.2

phases:
  install:
   commands:
     - echo Entering install phase...
     - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 649662587083.dkr.ecr.eu-west-1.amazonaws.com
  build:
    commands:
     - echo Build started on `date`
     - chmod -R 777 ./*
     - cd ./manager-api
     - ./gradlew build
     - docker build -t volunteer-ua .
     - docker tag volunteer-ua:latest 649662587083.dkr.ecr.eu-west-1.amazonaws.com/volunteer-ua:latest
     - docker push 649662587083.dkr.ecr.eu-west-1.amazonaws.com/volunteer-ua:latest