version: 0.2

phases:
  install:
   commands:
     - echo Entering install phase...
     - echo Nothing to do now
  build:
    commands:
     - echo Build started on `date`
     - chmod -R 777 ./*
     - cd ./manager-api
     - ./gradlew build -x test
     - docker build -t volunteer-ua .
     - docker tag volunteer-ua:latest 649662587083.dkr.ecr.eu-west-1.amazonaws.com/volunteer-ua:latest
     - docker push 649662587083.dkr.ecr.eu-west-1.amazonaws.com/volunteer-ua:latest