spring:
  application:
    name: "manager-api"
  mvc:
    throwExceptionIfNoHandlerFound: true
  resources:
    add-mappings: false
  datasource:
    driverClassName: 'org.postgresql.Driver'
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: 'validate'
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        format_sql: false
  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: 'startup'

server:
  port: 8080
  
---
spring:
  profiles: local
  datasource:
    url: 'jdbc:postgresql://localhost:5432/volunteer'
    username: 'postgres'
    password: 'root'
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    secret: "secret"
    access-token-ttl: 30m
    refresh-token-ttl: 1h

cache:
  type: "db"
  verification-code-ttl: 10m

---
spring:
  profiles: aws
  datasource:
    url: 'jdbc:postgresql://${VOLUNTEER_DB_HOST}:5432/volunteer'
    username: '${VOLUNTEER_DB_USER}'
    password: '${VOLUNTEER_DB_PASSWORD}'

security:
  jwt:
    secret: '${VOLUNTEER_JWT_SECRET}'
    access-token-ttl: 30m
    refresh-token-ttl: 1h

cache:
  type: "redis"
  verification-code-ttl: 10m
  
turbosms:
  sender: '${TURBOSMS_SENDER}'
  authtoken: '${TURBOSMS_TOKEN}'
  enabled: true
